# Generated by Django 3.2.9 on 2021-12-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysource',
            name='contact_demoed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='companysource',
            name='contact_email_autoresponder',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='companysource',
            name='contact_email_bounced',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='companysource',
            name='contact_email_clicked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='companysource',
            name='contact_email_no_reply',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='companysource',
            name='contact_email_open',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='companysource',
            name='contact_email_replied',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='companysource',
            name='contact_email_sent',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='companysource',
            name='contact_email_spamblocked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='companysource',
            name='contact_email_unsubscribed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='companysource',
            name='contact_has_pending_email_arcgate_request',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='companysource',
            name='contact_unlocked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
