# Generated by Django 3.2.9 on 2021-12-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211225_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='start_processing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.CharField(blank=True, choices=[('UPLOADED', 'UPLOADED'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED')], default='UPLOADED', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='stop_processing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='task_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
