# Generated by Django 3.2.9 on 2022-01-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_file_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='created_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='updated_number',
            field=models.IntegerField(default=0),
        ),
    ]
