# Generated by Django 3.2.9 on 2022-01-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220103_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysource',
            name='company_address',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='companysource',
            name='work_direct_phone',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
